### ISSUE TITLE
Cannot remove/reduce items from 'model'

### ISSUE THREAD

**Issue by justindarc** [gaia-components/gaia-fast-list#12]
In order to implement search functionality, we need the ability to continuously re-set the `model` property on the list. Currently, when trying to set the list's `model` to an empty array after already having a `model` with multiple items results in nothing changing. It should be expected that setting the `model` to an empty array would cause the list to re-render and remove all previously-rendered list items from being displayed.

**Comment by wilsonpage** [comment]
Fixed by https://github.com/gaia-components/fast-list/pull/74
