### ISSUE TITLE
Allow Blobs to be returned from getItemImageSrc()

### ISSUE THREAD

**Issue by arcturus** [gaia-components/gaia-fast-list#14]
It will be nice if we could pass blobs directly to the component for each row, and the component is smart enough to know when it has to call `window.createObjectURL`, revoke them, or have a policy for caching images.

**Comment by wilsonpage** [comment]
As discussed we're going to accept blobs to be returned by the user from `.getItemImageSrc()` and `createObjectURL` internally. We will cache the ObjectURL until we reach a defined memory limit, at which point we will start to `revokeObjectURL` to make space for new images.
