### ISSUE TITLE
Fire a 'firstrender' event

### ISSUE THREAD

**Issue by wilsonpage** [gaia-components/gaia-fast-list#24]
If we tell the app when the list has rendered something, they can make the decision when to reveal the page to the user. This will be required if we are going to do any `<body hidden>` tricks to prevent Gecko wasting cycles rendering partially complete UI.

**Comment by etiennesegonzac** [comment]
Makes sense. The app will probably add the listener right away, before there's a component to get the |.rendered| promise from.

So an event sounds good :)
